language: java
jdk:
- openjdk6
env:
  global:
  - secure: O4VrA8kvfODwfdJ4blIbW1wR4LZfFDJTpshN/ubmsnhyQKaj8cadi+6qNR+TqDjsrVWWErZtgvro4XRCqS2XgFkVDah0lcw7ZgzgkIEdIM0MegBw1aH8dZ8LDG8WbdBWlLT/EeDAyfIQ8ahlhDmFSqeuOHLsNZWg+Z5sV5/8GiY=
  - secure: lPi1cmuIEVZC6se/1/dBBW8qpYVWh8O91PaRUF6KP0w5VqoT/8r4DU1sz2dDL5/zLe+DiRDF12V5pnldYgkk0RbdN6yZJ8wo2nKeZ/xE+aTplZSb2pm5XwtEDld6gCNbqEqmYoLCM0VoDDYIb/cMUleQB894Nyxft3CJsU3xOhE=
  - secure: B1EHJleQIMCOVHq/6PB4TjufLl8Q7uX2JeGpuhBz5KzvCuWlWBH3g3WhKZijywH05H62egL25mAtRKL5gl82BDRJh57WxlAiXAG8m2/4nq/RHtGQO1mEKUszzxE4dH1yJiYgqqqdCIp3uBrEYvJXM1GeP1sZff0v3bE60y3ZHG0=
  - secure: pe9K5eGNi0qFXILRu3ZiXR/T6iMtNhQHOeOJgg7gcH+CpznAuuC4j15ZSQPFjlU3vSNtooUqoG4SA/fE0ePYqk3Uc8i2UWCz3HAa2CE7JMLVJc1sX7B3LfDh/oHmsXZ6bvUcvytCjw9Med7Z7a851w6/Y4NfjooB1lTHdbozSU8=

  matrix:
  #- BROWSER="internet explorer" VERSION=8
  #- BROWSER="internet explorer" VERSION=9
  #- BROWSER="internet explorer" VERSION=10
  #- BROWSER="internet explorer" VERSION=11
  - BROWSER="firefox" VERSION=31
  #- BROWSER="chrome" VERSION=37

after_script: gradle uploadArchives

addons:
  sauce_connect: true
